# dev enviroment setup

version: '3'

services:

  nginx:
    ports:
      - 80:80
      - 443:443

  duckdns:
    env_file:
      - './resources/emon.docker-env'

  web:
    volumes:
      # Disable access to /php-info.php for security reasons
      - /dev/null:/var/www/html/php-info.php
    env_file:
      - './resources/emon.docker-env'
    environment:
      # Set production enviroment variable flag, not currently used for anything but might be of use in the future
      PRODUCTION: 'true'

  db:
    env_file:
      - './resources/emon.docker-env'

  redis:
    env_file:
      - './resources/emon.docker-env'

